<?php
//Crie um vetor para a linha principal;
//Crie uma matriz para as linhas secundarias;
//Deve ficar da seguinte forma:
//vetor: 
//LINHA0 - PRODUTO, MARCA, QUANTIDADE, QUANTIDADE, PREÇO;
//MATRIZ:
//LINHA1 - PRODUTO(L0-C0), MARCA(L0-C1), QUANTIDADE(L0-C2), QUANTIDADE(L0-C3), PREÇO(L0-C4);
//LINHA2 - PRODUTO(L1-C0), MARCA(L1-C1), QUANTIDADE(L1-C2), QUANTIDADE(L1-C3), PREÇO(L1-C4);
//LINHA3 - PRODUTO(L2-C0), MARCA(L2-C1), QUANTIDADE(L2-C2), QUANTIDADE(L2-C3), PREÇO(L2-C4);
//LINHA4 - PRODUTO(L3-C0), MARCA(L3-C1), QUANTIDADE(L3-C2), QUANTIDADE(L3-C3), PREÇO(L3-C4);
?>